### PR TITLE
Update MainScript.js

### PR DESCRIPTION
**Pull request by Gnowtest1**
Great

### CODE REVIEW

**Comment by qconrad** [comment]
Hi. Could you please provide some more information on what this change is trying to accomplish?

**Comment by Halloween20** [comment]
Can you add the Narrations the forecast ?

**Comment by Halloween20** [comment]
Can you Please fix this Weather Radar it's seems to be laggy

**Comment by Halloween20** [comment]
Are you fixing Something on this Emulator ?

**Pull request closed without merging**
